### ISSUE TITLE
Error while installing the attack range by using dockers

### ISSUE THREAD

**Issue by Mohan-veera** [splunk/attack_range#755] opened 2023-02-16 16:29 UTC
Hello team,

I am trying to install Splunk attack range simulator in Ubuntu 18.04 in AWS by using the dockers. During the installation the instances were created succesfully and there was no error generated. And after the Terraform initialization i am getting an error as below. Can anyone help me to resolve the issue ASAP...

![image](https://user-images.githubusercontent.com/125536973/219427597-22ca935f-fc77-42a0-9342-96a8ad02a344.png)

**Comment by gstefan-akryl** [comment] 2023-02-20 10:31
Hi, 

Have same issue on AWS running from MacOS.

**Comment by patel-bhavin** [comment] 2023-02-21 02:12
Can you share what your attack_range.yml config looks like? We haven't encountered this error before. Do you have aany stale .tf files in the `terraform/aws` directory? I would consider starting restarting from cloning the repo. Please always consider running destroy command before building any new resources. I am happy to jump on a zoom to help you troubleshoot this

**Comment by gstefan-akryl** [comment] 2023-02-21 12:49
Standard, generated by attack_range configure. 

```
general:
  cloud_provider: aws
  attack_range_password: <password>
  use_prebuilt_images_with_packer: '1'
  key_name: <key_name>
  ip_whitelist: <...>
  range_name: ar
aws:
  private_key_path: .....<path>
  region: us-east-1
windows_servers:
- hostname: ar-win-1
  windows_image: windows-2016-v3-0-0
```

**Comment by patel-bhavin** [comment] 2023-02-22 01:04
hello @gstefan-akryl 
we have had some bug reports for how attack_range.yml has an incorrect attribute. The proposed fix for that issue is in this https://github.com/splunk/attack_range/pull/760

However, for your issue: can you try changing `range_name: ar` to `attack_range_name: ar` in your attack_range.yml file and try re running the show command?

**Comment by gstefan-akryl** [comment] 2023-02-22 10:26
It did not change anything in behaviour. Still having:

```
╷
│ Error: Unsupported attribute
│
│   on modules/windows/resources.tf line 20, in data "aws_ami" "windows_ami":
│   20:     values = [var.windows_servers[count.index].windows_ami]
│     ├────────────────
│     │ count.index is 0
│     │ var.windows_servers is list of object with 1 element
│
│ This object does not have an attribute named "windows_ami".
╵
2023-02-22 11:24:37,944 - INFO - attack_range - [action] > show

```

**Comment by Logeshrathinakumar** [comment] 2023-02-22 16:12
Hello guys,

Same issue from my side also i have changed from range_name: ar to attack_range_name: ar in attack_range.yml but still the issue not resolved... Please help me to resolve the issue....

**Comment by j00c3** [comment] 2023-02-22 23:32
> It did not change anything in behaviour. Still having:
> 
> ```
> ╷
> │ Error: Unsupported attribute
> │
> │   on modules/windows/resources.tf line 20, in data "aws_ami" "windows_ami":
> │   20:     values = [var.windows_servers[count.index].windows_ami]
> │     ├────────────────
> │     │ count.index is 0
> │     │ var.windows_servers is list of object with 1 element
> │
> │ This object does not have an attribute named "windows_ami".
> ╵
> 2023-02-22 11:24:37,944 - INFO - attack_range - [action] > show
> ```

I can confirm that if you make the below mod, it'll work

File: `terraform/aws/modules/windows/resources.tf`
Line: 20

Change `values = [var.windows_servers[count.index].windows_ami]` to `values = [var.windows_servers[count.index].windows_image]`

![image](https://user-images.githubusercontent.com/9037100/220787398-56160d3e-4dbc-4447-a353-1467f62566a8.png)

**Comment by gstefan-akryl** [comment] 2023-02-25 09:15
The problem is with prebuilt images. When I disable them in configuration environment is created. 
attack_range.yml:

```
general:
  ....
  use_prebuilt_images_with_packer: '0'
  ....
aws:
  
```

**Comment by edwardxwu** [comment] 2023-03-13 00:20
\+1 I am running into the same issue

**Comment by P4T12ICK** [comment] 2023-03-14 10:59
this should be fixed. thank you for reporting it.

**Closed as completed by P4T12ICK** 2023-03-14 10:59 UTC
